# Generated by Django 5.2 on 2025-04-19 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizcion', models.DateTimeField(auto_now=True)),
                ('tipo_pago_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipopago')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=15)),
                ('cui', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('empresa', models.CharField(max_length=250)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.proveedor'),
        ),
    ]
