# Generated by Django 5.2 on 2025-07-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_rename_rolusuario_rolusuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolUsuarios',
        ),
    ]
