# Generated by Django 5.2 on 2025-07-27 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_rolusuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RolUsuarios',
            new_name='RolUsuario',
        ),
    ]
