# Generated by Django 5.2 on 2025-04-19 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=15)),
                ('cui', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('observacion', models.TextField()),
                ('nota', models.TextField()),
                ('perdida', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('garantia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('costo_servicio', models.FloatField(default=0)),
                ('observacion', models.TextField()),
                ('estado', models.BooleanField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('factura_emitida', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.cliente')),
                ('tipo_pago_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipopago')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='garantia',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.FloatField(default=0)),
                ('descripcion', models.TextField()),
                ('no_autorizacion', models.CharField(max_length=60)),
                ('bien_servicio', models.CharField(choices=[('B', 'Bien'), ('S', 'Servicio')], default='S', max_length=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('ganancia', models.FloatField(default=0)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.tiposervicio'),
        ),
    ]
