# Generated by Django 5.2 on 2025-07-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleservicio',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
