# Generated by Django 5.2 on 2025-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='nota',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
