# Generated by Django 5.2 on 2025-09-20 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_serviciousuario_usuario_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciousuario',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='serviciousuario',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_tecnicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
