# Generated by Django 5.2 on 2025-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_serviciousuario_servicio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cotizacion',
            field=models.BooleanField(default=False),
        ),
    ]
