# Generated by Django 5.2 on 2025-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(blank=True, default='', upload_to='producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='img2',
            field=models.ImageField(blank=True, default='', upload_to='producto'),
            preserve_default=False,
        ),
    ]
